Happyr\UserProjectBundle\Entity\Project:
  type: entity
  table: HappyrUserProject
  repositoryClass: Happyr\UserProjectBundle\Entity\ProjectRepository
  lifecycleCallbacks:
    preUpdate: [updateUpdatedAt]
  oneToMany:
    objects:
      targetEntity: Happyr\UserProjectBundle\Model\ProjectObjectInterface
      mappedBy: project
      cascade: [persist]
  manyToMany:
    users:
      targetEntity: Happyr\UserProjectBundle\Model\ProjectMemberInterface
      joinTable:
        name: HappyrUserProject_Users
        joinColumns:
          project_id:
            referencedColumnName: id
        inverseJoinColumns:
          user_id:
            referencedColumnName: id

  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    public:
      type: boolean
    permissions:
      type: array
    name:
      type: string
      length: 255
    description:
      type: text
      nullable: true
    createdAt:
      type: datetime
    updatedAt:
      type: datetime