happyr_user_project_project:
  resource: "@HappyRUserProjectBundle/Resources/config/routing/project.yml"
  prefix:   /projects

happyr_user_project_users:
  resource: "@HappyRUserProjectBundle/Resources/config/routing/users.yml"
  prefix:   /projects/{id}/users
  requirements:
    id:  \d+

happyr_user_project_objects:
  resource: "@HappyRUserProjectBundle/Resources/config/routing/objects.yml"
  prefix:   /projects/{id}/objects
  requirements:
    id:  \d+
