parameters:

services:
  happyr.user.project.permission_manager:
    class: Happyr\UserProjectBundle\Manager\PermissionManager
    arguments: [@security.acl.provider]


  happyr.user.project.project_manager:
    class: Happyr\UserProjectBundle\Manager\ProjectManager
    arguments:
      - @doctrine.orm.entity_manager
      - @happyr.user.project.permission_manager
      - @happyr.user.project.project_factory
      - @event_dispatcher

  happyr.user.project.secure_project_manager:
    class: Happyr\UserProjectBundle\Manager\SecureProjectManager
    arguments:
      - @doctrine.orm.entity_manager
      - @happyr.user.project.permission_manager
      - @happyr.user.project.project_factory
      - @event_dispatcher
    calls:
        - [setSecurityManager, [@happyr.user.project.security_manager]]

  happyr.user.project.project_factory:
    class: Happyr\UserProjectBundle\Factory\ProjectFactory
    arguments: [@doctrine.orm.entity_manager, @happyr.user.project.permission_manager]

  happyr.user.project.project_service:
    class: Happyr\UserProjectBundle\Service\ProjectService
    arguments: [@doctrine.orm.entity_manager, @happyr.user.project.project_factory]

  happyr.user.project.security_manager:
    class: Happyr\UserProjectBundle\Manager\SecurityManager
    arguments: [@security.authorization_checker]