parameters:
  happyr.user.project.permission_manager.class: Happyr\UserProjectBundle\Manager\PermissionManager
  happyr.user.project.mailer.class: Happyr\UserProjectBundle\Services\MailerService
  happyr.user.project.project_manager.class: Happyr\UserProjectBundle\Manager\ProjectManager
  happyr.user.project.secure_project_manager.class: Happyr\UserProjectBundle\Manager\SecureProjectManager
  happyr.user.project.project_factory.class: Happyr\UserProjectBundle\Factory\ProjectFactory
  happyr.user.project.project_service.class: Happyr\UserProjectBundle\Services\ProjectService
  happyr.user.project.security_manager.class: Happyr\UserProjectBundle\Manager\SecurityManager

services:
  happyr.user.project.permission_manager:
    class: %happyr.user.project.permission_manager.class%
    arguments: [@security.acl.provider]


  happyr.user.project.project_manager:
    class: %happyr.user.project.project_manager.class%
    arguments:
      - @doctrine.orm.entity_manager
      - @happyr.user.project.permission_manager
      - @happyr.user.project.project_factory
      - @event_dispatcher

  happyr.user.project.secure_project_manager:
    class: %happyr.user.project.secure_project_manager.class%
    arguments:
      - @doctrine.orm.entity_manager
      - @happyr.user.project.permission_manager
      - @happyr.user.project.project_factory
      - @event_dispatcher
    calls:
        - [setSecurityManager, [@happyr.user.project.security_manager]]

  happyr.user.project.project_factory:
    class: %happyr.user.project.project_factory.class%
    arguments: [@doctrine.orm.entity_manager, @happyr.user.project.permission_manager]

  happyr.user.project.project_service:
    class: %happyr.user.project.project_service.class%
    arguments: [@doctrine.orm.entity_manager, @happyr.user.project.project_factory]

  happyr.user.project.security_manager:
    class: %happyr.user.project.security_manager.class%
    arguments: [@security.context]