happyr_user_project_object_add:
  path:      /add
  defaults:  { _controller: HappyRUserProjectBundle:Object:add }
  methods:  [POST]

happyr_user_project_object_remove:
  path:      /add/{object_id}/remove
  defaults:  { _controller: HappyRUserProjectBundle:Object:remove }
  methods:  [GET]
  requirements:
    object_id:  \d+

