#TODO you might have to set object_id to null..
happyr_user_project_user_add:
  path:      /add/{objectId}
  defaults:  { _controller: HappyRUserProjectBundle:User:add, objectId:0 }
  methods:  [POST]
  requirements:
    objectId:  \d+

happyr_user_project_user_edit:
  path:      /add/{user_id}/edit
  defaults:  { _controller: HappyRUserProjectBundle:User:edit }
  methods:  [POST]
  requirements:
    user_id:  \d+

happyr_user_project_user_remove:
  path:      /add/{user_id}/remove
  defaults:  { _controller: HappyRUserProjectBundle:User:remove }
  methods:  [GET]
  requirements:
    user_id:  \d+

